[2026-09-16 21:23:00]

diff --git a/qrcreate b/qrcreate
--- a/qrcreate
+++ b/qrcreate
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-version='3.0.0'
+version='3.1.0'
 data=
 link='nolink'
 ofname='qr'
@@ -43,6 +43,18 @@ Copyright (c) 2026 Yavuz Köroğlu
                     ;;
                 *)
                     data="${data}${1}"
+                    ;;
+            esac
+            ;;
+        -d=*|--data-str=*)
+            newdata="${1#*=}"
+            case "${newdata}" in
+                '')
+                    echo "ERROR: No data given after -d= or --data-str=" >&2
+                    exit 1;
+                    ;;
+                *)
+                    data="${data}${newdata}"
                     ;;
             esac
             ;;
@@ -101,6 +113,25 @@ NOTE:
                     ;;
             esac
             ;;
+        -i=*|--input-filename=*)
+            ifname="${1#*=}"
+            echo $ifname
+            case "${ifname}" in
+                -*|'')
+                    echo "ERROR: No FILENAME given after -i= or --input-filename=." >&2
+                    exit 1
+                    ;;
+                *)
+                    if [[ -f "${ifname}" ]]
+                    then
+                        data="${data}$(cat ${ifname})"
+                    else
+                        echo "ERROR: No such file -- '${ifname}'." >&2
+                        exit 1
+                    fi
+                    ;;
+            esac
+            ;;
         -l|--link)
             link='link'
             ;;
@@ -112,6 +143,17 @@ NOTE:
                     ;;
                 *)
                     echo "ERROR: Unknown level ${1}, it must be L, M, Q, or H." >&2
+                    exit 1
+                    ;;
+            esac
+            ;;
+        -L=*|--level=*)
+            level="${1#*=}"
+            case "${level}" in
+                L|M|Q|H)
+                    ;;
+                *)
+                    echo "ERROR: Unknown level ${level}, it must be L, M, Q, or H." >&2
                     exit 1
                     ;;
             esac
@@ -131,6 +173,15 @@ NOTE:
                     ;;
             esac
             ;;
+        -N=*|--nruns=*)
+            nruns="${1#*=}"
+            case "${nruns}" in
+                ''|*[!0-9]*)
+                    echo "ERROR: Missing valid NUMBER after -n= or --nruns=." >&2
+                    exit 1
+                    ;;
+            esac
+            ;;
         -o|--output-filename)
             shift
             case "${1}" in
@@ -140,6 +191,15 @@ NOTE:
                     ;;
                 *)
                     ofname="${1}"
+                    ;;
+            esac
+            ;;
+        -o=*|--output-filename=*)
+            ofname="${1#*=}"
+            case "${ofname}" in
+                -*|'')
+                    echo "ERROR: No FILENAME given after -o or --output-filename." >&2
+                    exit 1
                     ;;
             esac
             ;;
@@ -157,6 +217,21 @@ NOTE:
                     ;;
                 -*|'')
                     echo "ERROR: Missing NUMBER or 'auto' after -s or --size." >&2
+                    exit 1;
+                    ;;
+                *)
+                    echo "ERROR: Size must be 'auto' or a NUMBER btw. 1-40." >&2
+                    exit 1;
+                    ;;
+            esac
+            ;;
+        -S=*|--size=*)
+            size="${1#*=}"
+            case "${size}" in
+                auto|1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31|32|33|34|35|36|37|38|39|40)
+                    ;;
+                -*|'')
+                    echo "ERROR: Missing NUMBER or 'auto' after -s= or --size=." >&2
                     exit 1;
                     ;;
                 *)
