[2026-10-04 12:38:17]

diff --git a/qrcreate b/qrcreate
--- a/qrcreate
+++ b/qrcreate
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-version='3.1.1'
+version='3.1.2'
 data=
 link='nolink'
 ofname='qr'
@@ -76,7 +76,7 @@ processInputFile() {
         *)
             if [[ -f "${1}" ]]
             then
-                data="${data}$(cat ${1})"
+                data+=$(<"${1}")
             else
                 echo "ERROR: No such file -- '${1}'." >&2
                 exit 1
@@ -107,6 +107,11 @@ processNRuns() {
             nruns="${1}"
             ;;
     esac
+    if (( ${nruns} < 1 ))
+    then
+        echo "ERROR: The NUMBER after -n must be greater than zero." >&2
+        exit 1
+    fi
 }
 
 processOutputFile() {
@@ -122,19 +127,22 @@ processOutputFile() {
 }
 
 processSize() {
-    case "${1}" in
-auto|1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31|32|33|34|35|36|37|38|39|40)
-            size="${1}"
-            ;;
-        -*|'')
-            echo "ERROR: Missing NUMBER or 'auto' after -s or --size." >&2
+    if [[ "${1}" == 'auto' ]]
+    then
+        size='auto'
+    elif [[ ${1} =~ ^[0-9]+ ]]
+    then
+        if (( ${1} >= 1 && ${1} <= 40 ))
+        then
+            size=${1}
+        else
+            echo "ERROR: Size must be a NUMBER btw. 1-40." >&2
             exit 1;
-            ;;
-        *)
-            echo "ERROR: Size must be 'auto' or a NUMBER btw. 1-40." >&2
-            exit 1;
-            ;;
-    esac
+        fi
+    else
+        echo "ERROR: Missing NUMBER or 'auto' after -s or --size." >&2
+        exit 1;
+    fi
 }
 
 if ! command -v pdflatex >/dev/null 2>&1
@@ -248,17 +256,32 @@ if [[ "${size}" == "auto" ]]; then size=""; else size=",version=${size}"; fi
 
 job=${ofname%.pdf}
 
-for i in $(seq ${nruns})
+tmp=$(mktemp)
+status=$?
+if [ ${status} -ne 0 ]
+then
+    echo "ERROR: Cannot create a temporary file." >&2
+    exit 1
+fi
+
+printf '%s' "${data}" > "${tmp}"
+
+for i in {1..${nruns}}
 do
-pdflatex -jobname="${job}" <<EOF
+if ! pdflatex -jobname="${job}" <<EOF
 \documentclass{standalone}
+\usepackage{csvsimple}
 \usepackage{hyperref}
 \usepackage[${link}]{qrcodetikz}
 \begin{document}
-\qrcode[level=${level}${size},${pad}]{${data}}
+\csvreader[no head,respect all]{${tmp}}{}{\qrcode[level=${level}${size},${pad}]{\csvcoli}}
 \end{document}
 EOF
+then
+    echo "ERROR: pdflatex failed" >&2
+    rm -f "${tmp}"
+    exit 1
+fi
 done
 
-# Comment this for debugging
-rm -f "${job}".aux "${job}".log "${job}".out
+rm -f "${job}".aux "${job}".log "${job}".out "${tmp}"
